## NumPy library

In [ ]:
import numpy as np

In [ ]:
array1 = np.array([1, 2, 3])
print(array1)

[1 2 3]


In [ ]:
array2 = np.zeros(5)
print(array2)

[0. 0. 0. 0. 0.]


In [ ]:
array3 = np.ones(5)
print(array3)

[1. 1. 1. 1. 1.]


In [ ]:
array4 = np.empty(3) # مصفوفه من بيانات عشوائيه.. غير مهيئه
print(array4)

[1. 1. 1.]


In [ ]:
array5 = np.arange(5)
print(array5)

[0 1 2 3 4]


In [ ]:
array6 = np.arange(0, 25, 5)
print(array6)

[ 0  5 10 15 20]


In [ ]:
# Array of equal points
array7 = np.linspace(0, 36, 9)
print(array7)

[ 0.   4.5  9.  13.5 18.  22.5 27.  31.5 36. ]


In [ ]:
oned = np.arange(21)
print(oned, '\n')

print(oned.dtype)
print(oned.size)
print(oned.nbytes)
print(oned.shape)
print(oned.ndim) # ndim هو خاصية (attribute) تُستخدم للحصول على عدد الأبعاد (dimensions) للكائن. فمثلاً، إذا كانت oned مصفوفة ثنائية الأبعاد، فإن oned.ndim ستعيد القيمة 2.

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] 

int64
21
168
(21,)
1


كيفية معرفة عدد أبعاد المصفوفه https://monica.im/home/chat/Monica/monica?convId=conv%3A1c1a19a1-fe69-441f-a24c-447e008a62c2

In [ ]:
type(oned) # n-dimensional array

numpy.ndarray

In [ ]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])
print(matrix, '\n')
print(matrix.shape, '\n')
print(matrix.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

(4, 4) 

2


In [ ]:
reshaped_1d = matrix.reshape(16)
print(reshaped_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [ ]:
reshaped_2d = matrix.reshape(2, 8)
print(reshaped_2d)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [ ]:
new_array = matrix.reshape(2, 2, 2, 2)
print(new_array)
print('\n الشكل', new_array.shape)
print('عدد الأبعاد',new_array.ndim)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]

 الشكل (2, 2, 2, 2)
عدد الأبعاد 4


In [ ]:
print(matrix.reshape(3, 3)) # read the error text, and you will understand

ValueError: cannot reshape array of size 16 into shape (3,3)

In [ ]:
matrix.reshape(3, 3)

ValueError: cannot reshape array of size 16 into shape (3,3)

### Indexing and clicing in NumPy

In [ ]:
# الفهرسه والتقطيع في نمباي

In [ ]:
import numpy as np

one = np.arange(10)
print(one)
print(one[-1])
print(one[3])
print(one[:5])
print(one[2:-3])

[0 1 2 3 4 5 6 7 8 9]
9
3
[0 1 2 3 4]
[2 3 4 5 6]


In [ ]:
two = np.arange(21).reshape(3, 7)
print(two, '\n')

print(two[1])
print(two[1, 3])
print(two[:, 3])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]] 

[ 7  8  9 10 11 12 13]
10
[ 3 10 17]


In [ ]:
two[1, 3] = 100
print(two)

[[  0   1   2   3   4   5   6]
 [  7   8   9 100  11  12  13]
 [ 14  15  16  17  18  19  20]]


In [ ]:
two[1:, 4:] = 0
print(two)

[[  0   1   2   3   4   5   6]
 [  7   8   9 100   0   0   0]
 [ 14  15  16  17   0   0   0]]


In [ ]:
list1 = [1, 2, 3, 4, 5] * 0
print(list1)

[]


In [ ]:
list2 = [1, 2, 3, 4, 5]
s = list2 * 0
print(s)

[]


In [ ]:
res = [1, 2, 3] * [4, 5, 6] # لا يمكن ضرب قائمتين.. حتى لو كانتا بنفس الطول.. سنحصل على خطأ
print(res)

TypeError: can't multiply sequence by non-int of type 'list'

In [ ]:
array8 = np.array([1, 2, 3])
array9 = np.array([4, 5, 6])
print(array8 * array9)
print(array8 + array9)
print(array8 - array9)
print(array8 / array9)

[ 4 10 18]
[5 7 9]
[-3 -3 -3]
[0.25 0.4  0.5 ]


In [ ]:
import numpy as np

mask = np.ones_like(True, shape=(3, 7))
print(mask)

[[ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]]


In [ ]:
mask[1:,:] = False
print(mask)

[[ True  True  True  True  True  True  True]
 [False False False False False False False]
 [False False False False False False False]]


In [ ]:
import numpy as np

maskkk = np.ones_like(True, shape=(4, 4))
maskkk[2:, :] = False
print(maskkk)

[[ True  True  True  True]
 [ True  True  True  True]
 [False False False False]
 [False False False False]]


In [ ]:
##############
two = np.arange(21).reshape(3, 7)
print(two)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]


In [ ]:
mask = np.ones_like(True, shape=(3, 7))
mask[1:, :] = False
print(mask)

[[ True  True  True  True  True  True  True]
 [False False False False False False False]
 [False False False False False False False]]


In [ ]:
print('Filtered array:',two[mask])

Filtered array: [0 1 2 3 4 5 6]


In [ ]:
##############

In [ ]:
r = two < 5
print(r)

[[ True  True  True  True  True False False]
 [False False False False False False False]
 [False False False False False False False]]


In [ ]:
Filtered_values = two[two < 5]
print(Filtered_values)

[0 1 2 3 4]


In [ ]:
complex_condition = two[(two < 5) & (two % 2 == 0)]
print(complex_condition)

[0 2 4]


In [ ]:
import numpy as np

mask = np.ones_like(True, shape=(3, 7))
mask[1:, :] = False
print("Mask:\n", mask)

Mask:
 [[ True  True  True  True  True  True  True]
 [False False False False False False False]
 [False False False False False False False]]


In [ ]:
two = np.array([[33, 1, 2, 3, 4, 5, 6],
                [0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 0, 0]])

print(two[mask])

[33  1  2  3  4  5  6]


In [ ]:
result_mask = two < 5
print(result_mask)

[[False  True  True  True  True False False]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]]


In [ ]:
filtered_values = two[result_mask]
print(filtered_values)

[1 2 3 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [ ]:
filtered_values = two[two < 5]
print(filtered_values)

[1 2 3 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [ ]:
# complex_condition

complex_condition = two[(two < 5) & (two % 2 == 0)]
print(complex_condition)

[2 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [ ]:
import numpy as np

mask = np.ones_like(True, shape=(3, 7))
mask[1:, :] = False
print(mask)

[[ True  True  True  True  True  True  True]
 [False False False False False False False]
 [False False False False False False False]]


In [ ]:
two = np.array([[33, 1, 2, 3, 4, 5, 6],
                [0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 0, 0]])

print(two[mask])

[33  1  2  3  4  5  6]


In [ ]:
s = two < 0
print(s)

[[False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]]


In [ ]:
d = two > 1
d

array([[ True, False,  True,  True,  True,  True,  True],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False]])

In [ ]:
f = d
print(f)

[[ True False  True  True  True  True  True]
 [False False False False False False False]
 [False False False False False False False]]


### التمثيلات والنسخ في NumPy

In [ ]:
import numpy as np

a = np.arange(24).reshape(4, 6)
print('Array A: \n', a)

Array A: 
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [ ]:
b = a[:2, 3:]
print(b)

[[ 3  4  5]
 [ 9 10 11]]


In [ ]:
b[1, 1] = 55
print('Array B:\n', b)

Array B:
 [[ 3  4  5]
 [ 9 55 11]]


In [ ]:
# Create a copy of b

b = a[:2, 3:].copy()
print('Array B (copy): \n', b)

Array B (copy): 
 [[ 3  4  5]
 [ 9 55 11]]


In [ ]:
# Modify an element in the copy

b[1, 1] = -1
print(b)

[[ 3  4  5]
 [ 9 -1 11]]


In [ ]:
print(a, '\n')
print(b)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 55 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]] 

[[ 3  4  5]
 [ 9 -1 11]]


### طرق المصفوفة في NumPy - Методы массива

In [ ]:
import numpy as np

data = np.arange(12).reshape(3, 4)
print('data:\n', data, '\n')

print(data.min())
print(data.max())
print(data.sum())
print(data.mean())
print(data.std()) # Standard deviation
print(data.sum(1))
print(data.sum(0))
print(data.argmax(1))
print(data.argmax(0))

data:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

0
11
66
5.5
3.452052529534663
[ 6 22 38]
[12 15 18 21]
[3 3 3]
[2 2 2 2]


In [ ]:
A1 = np.arange(9).reshape(3, 3)
print('A1:\n', A1)
print('\n Transposed A:\n', A1.T) # Transpose

A2 = np.ones(9).reshape(3, 3)
print('\n A2:\n', A2)
print('\n A1 @ A2:\n', A1 @ A2) # Matrix multiplication

print('\n Dot product:\n', A1.dot(A2)) # Dot product
print('\n Diagonal of the matrix:\n', A1.diagonal()) # Diagonal of the matrix

A1:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

 Transposed A:
 [[0 3 6]
 [1 4 7]
 [2 5 8]]

 A2:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

 A1 @ A2:
 [[ 3.  3.  3.]
 [12. 12. 12.]
 [21. 21. 21.]]

 Dot product:
 [[ 3.  3.  3.]
 [12. 12. 12.]
 [21. 21. 21.]]

 Diagonal of the matrix:
 [0 4 8]


In [ ]:
print(A1.dtype)
print(A1.size)
print(A1.nbytes, '\n')

# Create an array with int8 type
# C = np.arange(9).reshape(3, 3)  # dtype == int16
C = np.arange(9, dtype=np.int8).reshape(3, 3)
print(C)
print('\n', C.dtype)
print('\n', C.nbytes)

int64
9
72 

[[0 1 2]
 [3 4 5]
 [6 7 8]]

 int8

 9


In [ ]:
# تحويل البيانات

C[1, 1] = 0.5
print(C[1, 1])

0


البث في بايثون Broadcasting

In [ ]:
import numpy as np

A1 = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

A2 = np.array([[1, 1, 1],
              [1, 1, 1],
              [1, 1, 1]])

print('Result:')
print('A1:\n', A1)
print('A2:\n', A2)
print(f'A1 {A1.shape} + A2 {A2.shape} = A3 {(A1 + A2).shape}:\n', A1 + A2)

Result:
A1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
A2:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
A1 (3, 3) + A2 (3, 3) = A3 (3, 3):
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
import numpy as np

A1 = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

A2 = np.array([1, 1, 1]) # مصفوفة أي2 كأحادية البعد

print('Result:')
print('A1:\n', A1)
print('A2:\n', A2)
print(f'A1 {A1.shape} + A2 {A2.shape} = A3 {(A1 + A2).shape}:\n', A1 + A2)

Result:
A1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
A2:
 [1 1 1]
A1 (3, 3) + A2 (3,) = A3 (3, 3):
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
import numpy as np

A1 = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

A2 = 1 # مصفوفة أي2 كعدد صحيح

print('Result:')
print('A1:\n', A1)
print('A2:\n', A2)
print(f'A1 {A1.shape} + A2 (int) = A3 {(A1 + A2).shape}:\n', A1 + A2)

Result:
A1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
A2:
 1
A1 (3, 3) + A2 (int) = A3 (3, 3):
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
# reshape()

import numpy as np

s = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
ss = s.reshape(2, 3, 2)
print(ss)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
import numpy as np

a = np.arange(10).reshape(2, 1, 5)
b = np.arange(14).reshape(2, 7, 1)

print('a:\n', a)
print('b:\n', b)
print(f'\n\n a {a.shape} + b {b.shape} = c {(a + b).shape}:\n\n', a + b)

a:
 [[[0 1 2 3 4]]

 [[5 6 7 8 9]]]
b:
 [[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]
  [10]
  [11]
  [12]
  [13]]]


 a (2, 1, 5) + b (2, 7, 1) = c (2, 7, 5):

 [[[ 0  1  2  3  4]
  [ 1  2  3  4  5]
  [ 2  3  4  5  6]
  [ 3  4  5  6  7]
  [ 4  5  6  7  8]
  [ 5  6  7  8  9]
  [ 6  7  8  9 10]]

 [[12 13 14 15 16]
  [13 14 15 16 17]
  [14 15 16 17 18]
  [15 16 17 18 19]
  [16 17 18 19 20]
  [17 18 19 20 21]
  [18 19 20 21 22]]]


الدوال الرياضيه في NumPy and SciPy

In [ ]:
from numpy import poly1d

p1 = poly1d([3, 5, 0, 1])
print(p1)

   3     2
3 x + 5 x + 1


In [ ]:
from numpy import poly1d

p2 = poly1d((3, 5, 0, 1), True)
print('poly1d\n', p2)

print('\nvalue of poly1d at x=6:\n', p2(6))

poly1d
    4     3      2
1 x - 9 x + 23 x - 15 x

value of poly1d at x=6:
 90.0


In [ ]:
# العمليات على متعددات الحدود
# operations on polynomials

print(p1 * p2)
print('\n', p1 + p2)
print('\n', p2.deriv())
print('\n', p2.integ)
print('\np1 ==>>', p1.deriv)
print('\np1 ==>>', p1.integ)

   7      6      5      4      3      2
3 x - 22 x + 24 x + 71 x - 84 x + 23 x - 15 x

    4     3      2
1 x - 6 x + 28 x - 15 x + 1

    3      2
4 x - 27 x + 46 x - 15

 <bound method poly1d.integ of poly1d([  1.,  -9.,  23., -15.,   0.])>

p1 ==>> <bound method poly1d.deriv of poly1d([3, 5, 0, 1])>

p1 ==>> <bound method poly1d.integ of poly1d([3, 5, 0, 1])>


In [ ]:
import numpy as np

p = np.poly1d([1, -3, 2])
print(p)
print('\n\n', 'Polynomials at 5:', p(5))
print('\n', p.deriv())
print('\n', p.integ())

   2
1 x - 3 x + 2


 Polynomials at 5: 12

  
2 x - 3

         3       2
0.3333 x - 1.5 x + 2 x


### SciPy

In [ ]:
# SciPy library

In [ ]:
from scipy import special

factorial_value = special.factorial(3) # حساب العامل
print(factorial_value)

6.0


In [ ]:
# أمثلة إضافية على استخدام مكتبة SciPy

from scipy import special

combinations_value = special.comb(10, 2) # حساب عدد التوليفات
print(combinations_value)

45.0


In [ ]:
from scipy import special

permutations_value = special.perm(25, 4) # حساب عدد الترتيبات
print(permutations_value)

303600.0


### Pandas

In [ ]:
import pandas as pd

data = {
    'A': np.random.rand(5),
    'B': np.random.rand(5) * 100
}

df = pd.DataFrame(data)
print(df)

          A          B
0  0.395709  55.816310
1  0.394700  95.394249
2  0.886770  37.571164
3  0.743950  90.323671
4  0.751339  64.282112


In [ ]:
import pandas as pd

data = {
    'A': np.random.rand(5),
    'B': np.random.rand(5) * 100
}

df = pd.DataFrame(data)
print(df)

          A          B
0  0.971011   8.705205
1  0.606375  52.150960
2  0.586168  13.934193
3  0.977080  16.437622
4  0.525413  81.104225


In [ ]:
# mean value
# حساب المتوسط لكل عمود

mean_value = df.mean()
print('Mean value of each column:\n\n', mean_value)

Mean value of each column:

 A     0.733209
B    34.466441
dtype: float64


In [ ]:
# Pandas series

In [ ]:
import pandas as pd

data = [10, 20, 30, 40, 50]
series = pd.Series(data)
print(series)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [ ]:
import pandas as pd

data = [10, 20, 30, 40, 50]
labels = ['a', 'b', 'c', 'd', 'e']
custom_series = pd.Series(data, index=labels)
print(custom_series)

a    10
b    20
c    30
d    40
e    50
dtype: int64


In [ ]:
print(custom_series.min())
print(custom_series.max())
print(custom_series.mean())
print(custom_series.median())

10
50
30.0
30.0


In [ ]:
import pandas as pd

data = [1, 2, 3]
series = pd.Series(data, index=['one', 'two', 'three'])
print(series)

one      1
two      2
three    3
dtype: int64


In [ ]:
print(series['two'])

2


In [ ]:
series.loc['two']

np.int64(2)

In [ ]:
series.iloc[1]

np.int64(2)

In [ ]:
series.loc['one':'two']

one    1
two    2
dtype: int64

In [ ]:
series.iloc[0:1]

one    1
dtype: int64

In [ ]:
series[0:2]

one    1
two    2
dtype: int64

In [ ]:
import pandas as pd

data = ['Иванов Иван','Петров Петр','Сидоров Сидор']
names = pd.Series(data, index=['Пекарь', 'Сварщик', 'Маляр'], name='names') # Создаем Series из списка

emails_data = ['ivanov@ya.ru', 'petrov@ya.ru', 'sidorov@ya.ru']
emails = pd.Series(emails_data, index=['Пекарь', 'Сварщик', 'Маляр'], name='emails')

df = pd.concat([names, emails], axis=1)
print(df)

                 names         emails
Пекарь     Иванов Иван   ivanov@ya.ru
Сварщик    Петров Петр   petrov@ya.ru
Маляр    Сидоров Сидор  sidorov@ya.ru


In [ ]:
# Pandas DataFrame

In [ ]:
data = {
    'names': ['Иванов Иван', 'Петров Петр', 'Сидоров Сидор'], # أسماء الأشخاص
    'emails': ['ivanov@ya.ru', 'petrov@ya.ru', 'sidorov@ya.ru'], # عناوين البريد الإلكتروني
    'ages': [25, 30, 35] # أعمار الأشخاص
}

df = pd.DataFrame(data)
print(df)

           names         emails  ages
0    Иванов Иван   ivanov@ya.ru    25
1    Петров Петр   petrov@ya.ru    30
2  Сидоров Сидор  sidorov@ya.ru    35


In [ ]:
print(names)

Пекарь       Иванов Иван
Сварщик      Петров Петр
Маляр      Сидоров Сидор
Name: names, dtype: object


In [ ]:
print(names[2])

Сидоров Сидор


<ipython-input-354-63ca70730b04>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(names[2])


In [ ]:
print(df['emails'])

0     ivanov@ya.ru
1     petrov@ya.ru
2    sidorov@ya.ru
Name: emails, dtype: object


In [ ]:
print(df['names'])

0      Иванов Иван
1      Петров Петр
2    Сидоров Сидор
Name: names, dtype: object


In [ ]:
print(df.iloc[2])

names     Сидоров Сидор
emails    sidorov@ya.ru
ages                 35
Name: 2, dtype: object


In [ ]:
# تخصيص الفهارس

data = {
    'names': ['Иванов Иван', 'Петров Петр', 'Сидоров Сидор'], # أسماء الأشخاص
    'emails': ['ivanov@ya.ru', 'petrov@ya.ru', 'sidorov@ya.ru'], # عناوين البريد الإلكتروني
    'ages': [25, 30, 35] # أعمار الأشخاص
}

df = pd.DataFrame(data, index=['Worker1', 'Worker2', 'Worker3'])
df['salaries'] = [1000, 2000, 3000]
# df.loc['Worder2', 'salaries'] = 0000
# df.loc['Worder2', 'ages'] = 55
print(df)

                 names         emails  ages  salaries
Worker1    Иванов Иван   ivanov@ya.ru    25      1000
Worker2    Петров Петр   petrov@ya.ru    30      2000
Worker3  Сидоров Сидор  sidorov@ya.ru    35      3000


In [ ]:
# df.loc['Worder2', 'ages'] = 55
# print(df)

### To read and write files

In [ ]:
# قراءة وكتابة الملفات
# يمكننا قراءة بيانات من ملفات سي أس في او أكسيل وتحويلها إلى داتا فرايم


In [ ]:
import pandas as pd

df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


In [ ]:
# إنشاء قوائم تحتوي على بيانات
first_names = ['Ваня', 'Петя', 'Коля', 'Миша', 'Саша', 'Эдик', 'Маша', 'Вася']  # الأسماء الأولى
last_names = ['Николаев', 'Смирнов', 'Труфанов', 'Нечаев', 'Васильев', 'Романов', 'Сазонова', 'Полетаев']  # الألقاب
ages = [40, 17, 48, 16, 32, 18, 27, 32]  # الأعمار

data = {'first': first_names, 'last': last_names, 'ages': ages}

participants = pd.DataFrame(data)
participants = pd.DataFrame(data)
# print(participants)
print(participants)

  first      last  ages
0  Ваня  Николаев    40
1  Петя   Смирнов    17
2  Коля  Труфанов    48
3  Миша    Нечаев    16
4  Саша  Васильев    32
5  Эдик   Романов    18
6  Маша  Сазонова    27
7  Вася  Полетаев    32


In [ ]:
# إنشاء قوائم تحتوي على بيانات
first_names = ['Ваня', 'Петя', 'Коля', 'Миша', 'Саша', 'Эдик', 'Маша', 'Вася']  # الأسماء الأولى
last_names = ['Николаев', 'Смирнов', 'Труфанов', 'Нечаев', 'Васильев', 'Романов', 'Сазонова', 'Полетаев']  # الألقاب
ages = [40, 17, 48, 16, 32, 18, 27, 32]  # الأعمار

data = {'first': first_names, 'last': last_names, 'ages': ages}

participants = pd.DataFrame(data)
participants = pd.DataFrame(data, index=['P1', 'P2', 'P3', 'P4', 'P5', 'P6', 'P7', 'P8'])
# participants.index = ['P1', 'P2', 'P3', 'P4', 'P5', 'P6', 'P7', 'P8']
# print(participants)
print(participants)

   first      last  ages
P1  Ваня  Николаев    40
P2  Петя   Смирнов    17
P3  Коля  Труфанов    48
P4  Миша    Нечаев    16
P5  Саша  Васильев    32
P6  Эдик   Романов    18
P7  Маша  Сазонова    27
P8  Вася  Полетаев    32


In [ ]:
# إضافة أعمدة جديده

participants['nationality'] = ['Arabian'] * len(participants)
print(participants)

   first      last  ages nationality
P1  Ваня  Николаев    40     Arabian
P2  Петя   Смирнов    17     Arabian
P3  Коля  Труфанов    48     Arabian
P4  Миша    Нечаев    16     Arabian
P5  Саша  Васильев    32     Arabian
P6  Эдик   Романов    18     Arabian
P7  Маша  Сазонова    27     Arabian
P8  Вася  Полетаев    32     Arabian


In [ ]:
participants['Car'] = ['BMW'] * len(participants)
print(participants)

   first      last  ages nationality  Car
P1  Ваня  Николаев    40     Arabian  BMW
P2  Петя   Смирнов    17     Arabian  BMW
P3  Коля  Труфанов    48     Arabian  BMW
P4  Миша    Нечаев    16     Arabian  BMW
P5  Саша  Васильев    32     Arabian  BMW
P6  Эдик   Романов    18     Arabian  BMW
P7  Маша  Сазонова    27     Arabian  BMW
P8  Вася  Полетаев    32     Arabian  BMW


In [ ]:
# Make a DataFrame from list of lists

In [ ]:
# عند إنشاء داتا فرايم من قائمة قوائم سيتم تعيين أرقام صحيحه كأسماء الأعمده بشكل إفتراضي

import pandas as pd

data = [
    ["Ваня", "Николаев", 40],  # الصف الأول
    ["Петя", "Смирнов", 17],  # الصف الثاني
    ["Коля", "Труфанов", 48],  # الصف الثالث
    ["Миша", "Нечаев", 16],  # الصف الرابع
    ["Саша", "Васильев", 32],  # الصف الخامس
    ["Эдик", "Романов", 18],  # الصف السادس
    ["Маша", "Сазонова", 27],  # الصف السابع
    ["Вася", "Полетаев", 32]   # الصف الثامن
]

participants = pd.DataFrame(data)
print(participants)

      0         1   2
0  Ваня  Николаев  40
1  Петя   Смирнов  17
2  Коля  Труфанов  48
3  Миша    Нечаев  16
4  Саша  Васильев  32
5  Эдик   Романов  18
6  Маша  Сазонова  27
7  Вася  Полетаев  32


In [ ]:
# تخصيص أسماء الأعمده والفهارس

column_names = ['first', 'last', 'ages']
index_lables = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']

participants = pd.DataFrame(data, columns=column_names, index=index_lables)

print(participants)

  first      last  ages
a  Ваня  Николаев    40
b  Петя   Смирнов    17
c  Коля  Труфанов    48
d  Миша    Нечаев    16
e  Саша  Васильев    32
f  Эдик   Романов    18
g  Маша  Сазонова    27
h  Вася  Полетаев    32


In [ ]:
# تحديد أسماء الأعمدة
column_names = ['first', 'last', 'ages']  # أسماء الأعمدة

# تحديد أسماء الفهارس
index_labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']  # أسماء الفهارس

# إنشاء DataFrame مع أسماء الأعمدة والفهارس
participants = pd.DataFrame(data, columns=column_names, index=index_labels)

# طباعة DataFrame
print(participants)


  first      last  ages
a  Ваня  Николаев    40
b  Петя   Смирнов    17
c  Коля  Труфанов    48
d  Миша    Нечаев    16
e  Саша  Васильев    32
f  Эдик   Романов    18
g  Маша  Сазонова    27
h  Вася  Полетаев    32


In [ ]:
# حفظ ملف داتافرايم إلى ملف سي أس في
# باستخدام الدالة .to_csv

In [ ]:
participants.to_csv('./participants.csv') # Save a DataFrame file to csv file, in the same folder

In [ ]:
# Download files.. from GoogleColab

from google.colab import files

files.download('./participants.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
# شرح إنشاء DataFrame من ملف بالتفصيل



In [ ]:
import pandas as pd

participants2 = pd.read_csv('./participants.csv', index_col=0)

# participants2 = pd.read_csv('./participants.csv')

print(participants2)

  first      last  ages
a  Ваня  Николаев    40
b  Петя   Смирнов    17
c  Коля  Труфанов    48
d  Миша    Нечаев    16
e  Саша  Васильев    32
f  Эдик   Романов    18
g  Маша  Сазонова    27
h  Вася  Полетаев    32


### تحليل البيانات

In [ ]:
# تحليل البيانات
# عند تحميل البيانات، قد تكون هذه البيانات ضخمة بحيث لا يمكن عرضها بالكامل على الشاشة. لذلك، من المهم استكشاف بعض السجلات الأولى والأخيرة لفهم هيكل البيانات وكيفية التعامل معها.

In [ ]:
participants.head()

first      last  ages
a  Ваня  Николаев    40
b  Петя   Смирнов    17
c  Коля  Труфанов    48
d  Миша    Нечаев    16
e  Саша  Васильев    32

In [ ]:
participants.head(3)

first      last  ages
a  Ваня  Николаев    40
b  Петя   Смирнов    17
c  Коля  Труфанов    48

In [ ]:
participants.tail()

first      last  ages
d  Миша    Нечаев    16
e  Саша  Васильев    32
f  Эдик   Романов    18
g  Маша  Сазонова    27
h  Вася  Полетаев    32

In [ ]:
participants.tail(3)

first      last  ages
f  Эдик   Романов    18
g  Маша  Сазонова    27
h  Вася  Полетаев    32

In [ ]:
participants2.head()

first      last  ages
a  Ваня  Николаев    40
b  Петя   Смирнов    17
c  Коля  Труфанов    48
d  Миша    Нечаев    16
e  Саша  Васильев    32

In [ ]:
participants2.tail()

first      last  ages
d  Миша    Нечаев    16
e  Саша  Васильев    32
f  Эдик   Романов    18
g  Маша  Сазонова    27
h  Вася  Полетаев    32

In [ ]:
participants.describe()

ages
count   8.000000
mean   28.750000
std    11.572751
min    16.000000
25%    17.750000
50%    29.500000
75%    34.000000
max    48.000000

In [ ]:
participants.describe(percentiles=[0.1, 0.9])

ages
count   8.000000
mean   28.750000
std    11.572751
min    16.000000
10%    16.700000
50%    29.500000
90%    42.400000
max    48.000000

In [ ]:
import pandas as pd

participants2 = pd.read_csv('./participants.csv', index_col=0)

# participants2 = pd.read_csv('./participants.csv')

print(participants2)

In [ ]:
print(participants)

In [ ]:
import pandas as pd

# print('participants')
participants.csv

NameError: name 'participants' is not defined

In [ ]:
import pandas as pd

participants2 = pd.read_csv('./participants.csv', index_col=0)

print(participants2)

FileNotFoundError: [Errno 2] No such file or directory: './participants.csv'

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful

In [ ]:
Vimport pandas as pd
df = pd.read.csv('/content/drive/MyDrive/participants.csv')
print(df)

AttributeError: module 'pandas' has no attribute 'read'

In [ ]:
# استخدام الشرائح لاسترجاع الصفوف 3، 4، و5
participants2 = pd.DataFrame({
    'first': ['Миша', 'Саша', 'Эдик', 'Ваня', 'Петя', 'Коля'],
    'last': ['Нечаев', 'Васильев', 'Романов', 'Николаев', 'Смирнов', 'Труфанов'],
    'ages': [16, 32, 18, 40, 17, 48]
})

# عرض الصفوف 3، 4، و5
print("\nالصفوف من 3 إلى 5:")


NameError: name 'pd' is not defined

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd

# قراءة الملف من Google Drive
df = pd.read_csv('/content/drive/MyDrive/🟢TheFounder/participants.csv')

# عرض البيانات
print(df)


  Unnamed: 0 first      last  ages
0          a  Ваня  Николаев    40
1          b  Петя   Смирнов    17
2          c  Коля  Труфанов    48
3          d  Миша    Нечаев    16
4          e  Саша  Васильев    32
5          f  Эдик   Романов    18
6          g  Маша  Сазонова    27
7          h  Вася  Полетаев    32


In [ ]:
import pandas as pd

# استخدام الشرائح لاسترجاع الصفوف 3، 4، و5
participants2 = pd.DataFrame({
    'first': ['Миша', 'Саша', 'Эдик', 'Ваня', 'Петя', 'Коля'],
    'last': ['Нечаев', 'Васильев', 'Романов', 'Николаев', 'Смирнов', 'Труфанов'],
    'ages': [16, 32, 18, 40, 17, 48]
})

print(participants2)


  first      last  ages
0  Миша    Нечаев    16
1  Саша  Васильев    32
2  Эдик   Романов    18
3  Ваня  Николаев    40
4  Петя   Смирнов    17
5  Коля  Труфанов    48


In [ ]:
participants2.set_index(pd.Index(['a', 'b', 'c', 'd', 'e', 'f']), inplace=True)
print(participants2)

  first      last  ages
a  Миша    Нечаев    16
b  Саша  Васильев    32
c  Эдик   Романов    18
d  Ваня  Николаев    40
e  Петя   Смирнов    17
f  Коля  Труфанов    48


In [ ]:
participants2.loc['c']

first       Эдик
last     Романов
ages          18
Name: c, dtype: object

In [ ]:
participants2.loc['b':'e']

first      last  ages
b  Саша  Васильев    32
c  Эдик   Романов    18
d  Ваня  Николаев    40
e  Петя   Смирнов    17

In [ ]:
mask = [False, True, True, False, True, False]
masked_participants2 = participants2.loc[mask]
print(masked_participants2)

  first      last  ages
b  Саша  Васильев    32
c  Эдик   Романов    18
e  Петя   Смирнов    17


In [ ]:
mask = [True, False, False, True, True, False]
filtered_participants2 = participants2[mask]
print(filtered_participants2)

  first      last  ages
a  Миша    Нечаев    16
d  Ваня  Николаев    40
e  Петя   Смирнов    17


In [ ]:
print(participants2['c':'e'])

  first      last  ages
c  Эдик   Романов    18
d  Ваня  Николаев    40
e  Петя   Смирнов    17


In [ ]:
print(participants2[3:])

  first      last  ages
3  Ваня  Николаев    40
4  Петя   Смирнов    17
5  Коля  Труфанов    48


In [ ]:
participants2.loc['b':'d', ['first', 'ages']]

first  ages
b  Саша    32
c  Эдик    18
d  Ваня    40

In [ ]:
participants2.loc['c':'e', ['last', 'first']]

last first
c   Романов  Эдик
d  Николаев  Ваня
e   Смирнов  Петя

In [ ]:
participants2.loc['c':, 'ages']

c    18
d    40
e    17
f    48
Name: ages, dtype: int64

In [ ]:
participants2.loc[:, 'last']

a      Нечаев
b    Васильев
c     Романов
d    Николаев
e     Смирнов
f    Труфанов
Name: last, dtype: object

In [ ]:
participants2.loc[:, ['last', 'ages']]

last  ages
a    Нечаев    16
b  Васильев    32
c   Романов    18
d  Николаев    40
e   Смирнов    17
f  Труфанов    48

In [ ]:
participants2.loc[:'e', [False, True, False]]

last
a    Нечаев
b  Васильев
c   Романов
d  Николаев
e   Смирнов

In [ ]:
participants2.loc[:, [True, False, True]]

first  ages
a  Миша    16
b  Саша    32
c  Эдик    18
d  Ваня    40
e  Петя    17
f  Коля    48

In [ ]:
participants2.iloc[2]

first       Эдик
last     Романов
ages          18
Name: c, dtype: object

In [ ]:
participants2.iloc[2:4, [False, True, False]]

last
c   Романов
d  Николаев

In [ ]:
participants2.iloc[1:5, [False, True, True]]

last  ages
b  Васильев    32
c   Романов    18
d  Николаев    40
e   Смирнов    17

In [ ]:
participants2.iloc[1:4, 1:2]

last
b  Васильев
c   Романов
d  Николаев

In [ ]:
participants2.iloc[2:, 1:3]

last  ages
c   Романов    18
d  Николаев    40
e   Смирнов    17
f  Труфанов    48

In [ ]:
participants2.iloc[:, [True, False, True]]

first  ages
a  Миша    16
b  Саша    32
c  Эдик    18
d  Ваня    40
e  Петя    17
f  Коля    48

In [ ]:
mask = participants2['last'] == 'Смирнов'
print(mask)

a    False
b    False
c    False
d    False
e     True
f    False
Name: last, dtype: bool


In [ ]:
mask = participants2['ages'] == 40
print(mask)

a    False
b    False
c    False
d     True
e    False
f    False
Name: ages, dtype: bool


In [ ]:
mask = [True, False, True, False, True, False]
filtered_data = participants2.loc[mask]
print(filtered_data)

  first     last  ages
a  Миша   Нечаев    16
c  Эдик  Романов    18
e  Петя  Смирнов    17


In [ ]:
mask = (participants2['last'] == 'Смирнов') & (participants2['ages'] == 17)
print(mask)

a    False
b    False
c    False
d    False
e     True
f    False
dtype: bool


In [ ]:
mask = (participants2['first'] == 'Эдик') | (participants2['last'] == 'Смирнов') | (participants2['ages'] == 16)
print(mask)

a     True
b    False
c     True
d    False
e     True
f    False
dtype: bool


In [ ]:
mask = ~(participants2['ages'] == 17)
print(mask)

a     True
b     True
c     True
d     True
e    False
f     True
Name: ages, dtype: bool


In [ ]:
mask = ~(participants2['last'] == 'Смирнов')
print(mask)

a     True
b     True
c     True
d     True
e    False
f     True
Name: last, dtype: bool


In [ ]:
mask = (participants2['ages'] > 16) & (participants2['last'] != 'Смирнов') | (participants2['first'] == 'Саша')
fd = participants2[mask]
print(fd)

  first      last  ages
b  Саша  Васильев    32
c  Эдик   Романов    18
d  Ваня  Николаев    40
f  Коля  Труфанов    48


In [ ]:
mask = (participants2['ages'] > 16) & (participants2['last'] != 'Смирнов') | (participants2['first'] == 'Саша')
print(mask)

a    False
b     True
c     True
d     True
e    False
f     True
dtype: bool


In [ ]:
print(participants2)

  first      last  ages
a  Миша    Нечаев    16
b  Саша  Васильев    32
c  Эдик   Романов    18
d  Ваня  Николаев    40
e  Петя   Смирнов    17
f  Коля  Труфанов    48


In [ ]:
mask = participants2.loc[:, 'ages'] > 30
fd = participants2.loc[mask]
print(fd)

  first      last  ages
b  Саша  Васильев    32
d  Ваня  Николаев    40
f  Коля  Труфанов    48


In [ ]:
fd = participants2[participants2['ages'] > 30]
print(fd)

  first      last  ages
b  Саша  Васильев    32
d  Ваня  Николаев    40
f  Коля  Труфанов    48


In [ ]:
participants2.ages.min()

16

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/🟢TheFounder/participants.csv')

print(df)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
  Unnamed: 0 first      last  ages
0          a  Ваня  Николаев    40
1          b  Петя   Смирнов    17
2          c  Коля  Труфанов    48
3          d  Миша    Нечаев    16
4          e  Саша  Васильев    32
5          f  Эдик   Романов    18
6          g  Маша  Сазонова    27
7          h  Вася  Полетаев    32


### Participants2

In [ ]:
import pandas as pd

# استخدام الشرائح لاسترجاع الصفوف 3، 4، و5
participants2 = pd.DataFrame({
    'first': ['Миша', 'Саша', 'Эдик', 'Ваня', 'Петя', 'Коля'],
    'last': ['Нечаев', 'Васильев', 'Романов', 'Николаев', 'Смирнов', 'Труфанов'],
    'ages': [16, 32, 18, 40, 17, 48]
})

print(participants2)

  first      last  ages
0  Миша    Нечаев    16
1  Саша  Васильев    32
2  Эдик   Романов    18
3  Ваня  Николаев    40
4  Петя   Смирнов    17
5  Коля  Труфанов    48


In [ ]:
participants2.columns

Index(['first', 'last', 'ages'], dtype='object')

In [ ]:
participants2.rename(columns={'ages': 'Age'})

first      last  Age
0  Миша    Нечаев   16
1  Саша  Васильев   32
2  Эдик   Романов   18
3  Ваня  Николаев   40
4  Петя   Смирнов   17
5  Коля  Труфанов   48

In [ ]:
participants2.rename(columns={'ages': 'Age'}, inplace=True)

In [ ]:
participants2.columns

Index(['first', 'last', 'Age'], dtype='object')

In [ ]:
participants2['profession'] = ['Chef', 'Driver', 'Electrician', 'Programmer', 'Hairdresser', 'Architect']
participants2

first      last  Age   profession
0  Миша    Нечаев   16         Chef
1  Саша  Васильев   32       Driver
2  Эдик   Романов   18  Electrician
3  Ваня  Николаев   40   Programmer
4  Петя   Смирнов   17  Hairdresser
5  Коля  Труфанов   48    Architect

In [ ]:
participants2['Full_name'] = (participants2.loc[:, 'first'] + ' ' + participants2.loc[:, 'last'])
participants2

first      last  Age   profession      Full_name
0  Миша    Нечаев   16         Chef    Миша Нечаев
1  Саша  Васильев   32       Driver  Саша Васильев
2  Эдик   Романов   18  Electrician   Эдик Романов
3  Ваня  Николаев   40   Programmer  Ваня Николаев
4  Петя   Смирнов   17  Hairdresser   Петя Смирнов
5  Коля  Труфанов   48    Architect  Коля Труфанов

In [ ]:
participants2['Index_profi'] = (participants2.loc[:, 'Age'].astype(str) + ' ' + participants2.loc[:, 'profession'])
participants2

first      last  Age   profession      Full_name     Index_profi
0  Миша    Нечаев   16         Chef    Миша Нечаев         16 Chef
1  Саша  Васильев   32       Driver  Саша Васильев       32 Driver
2  Эдик   Романов   18  Electrician   Эдик Романов  18 Electrician
3  Ваня  Николаев   40   Programmer  Ваня Николаев   40 Programmer
4  Петя   Смирнов   17  Hairdresser   Петя Смирнов  17 Hairdresser
5  Коля  Труфанов   48    Architect  Коля Труфанов    48 Architect

In [ ]:
participants2.index = ['a', 'b', 'c', 'd', 'e', 'f']

In [ ]:
participants2

first      last  Age   profession      Full_name     Index_profi
a  Миша    Нечаев   16         Chef    Миша Нечаев         16 Chef
b  Саша  Васильев   32       Driver  Саша Васильев       32 Driver
c  Эдик   Романов   18  Electrician   Эдик Романов  18 Electrician
d  Ваня  Николаев   40   Programmer  Ваня Николаев   40 Programmer
e  Петя   Смирнов   17  Hairdresser   Петя Смирнов  17 Hairdresser
f  Коля  Труфанов   48    Architect  Коля Труфанов    48 Architect

In [ ]:
participants2.loc['d', 'Full_name'] = 'SSSSSSSS'
participants2

first      last  Age   profession      Full_name     Index_profi
a  Миша    Нечаев   16         Chef    Миша Нечаев         16 Chef
b  Саша  Васильев   32       Driver  Саша Васильев       32 Driver
c  Эдик   Романов   18  Electrician   Эдик Романов  18 Electrician
d  Ваня  Николаев   40   Programmer       SSSSSSSS   40 Programmer
e  Петя   Смирнов   17  Hairdresser   Петя Смирнов  17 Hairdresser
f  Коля  Труфанов   48    Architect  Коля Труфанов    48 Architect

In [ ]:
participants2['Age'] = participants2['Age'] + 1
participants2

first      last  Age   profession      Full_name     Index_profi
a  Миша    Нечаев   17         Chef    Миша Нечаев         16 Chef
b  Саша  Васильев   33       Driver  Саша Васильев       32 Driver
c  Эдик   Романов   19  Electrician   Эдик Романов  18 Electrician
d  Ваня  Николаев   41   Programmer       SSSSSSSS   40 Programmer
e  Петя   Смирнов   18  Hairdresser   Петя Смирнов  17 Hairdresser
f  Коля  Труфанов   49    Architect  Коля Труфанов    48 Architect

In [ ]:
participants2['Age'] = participants2['Age'].apply(lambda x: x + 1)
participants2

first      last  Age   profession      Full_name     Index_profi
a  Миша    Нечаев   18         Chef    Миша Нечаев         16 Chef
b  Саша  Васильев   34       Driver  Саша Васильев       32 Driver
c  Эдик   Романов   20  Electrician   Эдик Романов  18 Electrician
d  Ваня  Николаев   42   Programmer       SSSSSSSS   40 Programmer
e  Петя   Смирнов   19  Hairdresser   Петя Смирнов  17 Hairdresser
f  Коля  Труфанов   50    Architect  Коля Труфанов    48 Architect

In [ ]:
participants2['Age'] = participants2['Age'].apply(lambda x: x + 2)
participants2

first      last  Age   profession      Full_name     Index_profi
a  Миша    Нечаев   21         Chef    Миша Нечаев         16 Chef
b  Саша  Васильев   37       Driver  Саша Васильев       32 Driver
c  Эдик   Романов   23  Electrician   Эдик Романов  18 Electrician
d  Ваня  Николаев   45   Programmer       SSSSSSSS   40 Programmer
e  Петя   Смирнов   22  Hairdresser   Петя Смирнов  17 Hairdresser
f  Коля  Труфанов   53    Architect  Коля Труфанов    48 Architect

In [ ]:
participants2.iloc[2, 3] = 'ElEctRiCiAn'
participants2

first      last  Age   profession      Full_name     Index_profi
a  Миша    Нечаев   21         Chef    Миша Нечаев         16 Chef
b  Саша  Васильев   37       Driver  Саша Васильев       32 Driver
c  Эдик   Романов   23  ElEctRiCiAn   Эдик Романов  18 Electrician
d  Ваня  Николаев   45   Programmer       SSSSSSSS   40 Programmer
e  Петя   Смирнов   22  Hairdresser   Петя Смирнов  17 Hairdresser
f  Коля  Труфанов   53    Architect  Коля Труфанов    48 Architect

In [ ]:
participants2.iloc[3, 4] = 'Some Name'
participants2

first      last  Age   profession      Full_name     Index_profi
a  Миша    Нечаев   21         Chef    Миша Нечаев         16 Chef
b  Саша  Васильев   37       Driver  Саша Васильев       32 Driver
c  Эдик   Романов   23  ElEctRiCiAn   Эдик Романов  18 Electrician
d  Ваня  Николаев   45   Programmer      Some Name   40 Programmer
e  Петя   Смирнов   22  Hairdresser   Петя Смирнов  17 Hairdresser
f  Коля  Труфанов   53    Architect  Коля Труфанов    48 Architect

In [ ]:
participants2.Age += 9
participants2

first      last  Age   profession      Full_name     Index_profi
a  Миша    Нечаев   30         Chef    Миша Нечаев         16 Chef
b  Саша  Васильев   46       Driver  Саша Васильев       32 Driver
c  Эдик   Романов   32  ElEctRiCiAn   Эдик Романов  18 Electrician
d  Ваня  Николаев   54   Programmer      Some Name   40 Programmer
e  Петя   Смирнов   31  Hairdresser   Петя Смирнов  17 Hairdresser
f  Коля  Труфанов   62    Architect  Коля Труфанов    48 Architect

In [ ]:
participants2.replace('Some Name', 'Ahmedov', inplace=True)
participants2

first      last  Age   profession      Full_name     Index_profi
a  Миша    Нечаев   30         Chef    Миша Нечаев         16 Chef
b  Саша  Васильев   46       Driver  Саша Васильев       32 Driver
c  Эдик   Романов   32  ElEctRiCiAn   Эдик Романов  18 Electrician
d  Ваня  Николаев   54   Programmer        Ahmedov   40 Programmer
e  Петя   Смирнов   31  Hairdresser   Петя Смирнов  17 Hairdresser
f  Коля  Труфанов   62    Architect  Коля Труфанов    48 Architect

In [ ]:
participants2.replace('Ahmedov', 'AhmedovF', inplace=True)
participants2

first      last  Age   profession      Full_name     Index_profi
a  Миша    Нечаев   30         Chef    Миша Нечаев         16 Chef
b  Саша  Васильев   46       Driver  Саша Васильев       32 Driver
c  Эдик   Романов   32  ElEctRiCiAn   Эдик Романов  18 Electrician
d  Ваня  Николаев   54   Programmer       AhmedovF   40 Programmer
e  Петя   Смирнов   31  Hairdresser   Петя Смирнов  17 Hairdresser
f  Коля  Труфанов   62    Architect  Коля Труфанов    48 Architect

In [ ]:
participants2.replace('Programmer', 'ProgrammerML', regex=True, inplace=True)
participants2

first      last  Age    profession      Full_name      Index_profi
a  Миша    Нечаев   30          Chef    Миша Нечаев          16 Chef
b  Саша  Васильев   46        Driver  Саша Васильев        32 Driver
c  Эдик   Романов   32   ElEctRiCiAn   Эдик Романов   18 Electrician
d  Ваня  Николаев   54  ProgrammerML       AhmedovF  40 ProgrammerML
e  Петя   Смирнов   31   Hairdresser   Петя Смирнов   17 Hairdresser
f  Коля  Труфанов   62     Architect  Коля Труфанов     48 Architect

In [ ]:
# apply

def cap_word(w):
    dic = { 'а': 'a', 'б': 'b', 'в': 'v', 'г': 'g', 'д': 'd', 'е': 'e',
          'ё': 'yo','ж': 'zh','з': 'z', 'и': 'i', 'й': 'y', 'к': 'k',
          'л': 'l', 'м': 'm', 'н': 'n', 'о': 'o', 'п': 'p', 'р': 'r',
          'с': 's', 'т': 't', 'у': 'u', 'ф': 'f', 'х': 'h', 'ц': 'ts',
          'ч': 'ch','ш': 'sh','щ': 'shch','ъ': 'y', 'ы': 'y','ь': "'",
          'э': 'e', 'ю': 'yu','я': 'ya', 'А': 'A', 'Б': 'B', 'В': 'V',
          'Г': 'G', 'Д': 'D', 'Е': 'E', 'Ё': 'Yo', 'Ж': 'Zh', 'З': 'Z',
          'И': 'I', 'Й': 'Y', 'К': 'K', 'Л': 'L', 'М': 'M', 'Н': 'N',
          'О': 'O', 'П': 'P', 'Р': 'R', 'С': 'S', 'Т': 'T', 'У': 'U',
          'Ф': 'F', 'Х': 'H', 'Ц': 'Ts','Ч': 'Ch','Ш': 'Sh','Щ': 'Shch',
          'Ъ': 'Y', 'Ы': 'Y', 'Ь': "'", 'Э': 'E', 'Ю': 'Yu', 'Я': 'Ya' }

    t = str.maketrans(dic)
    return w.translate(t)

In [ ]:
participants2['Eng'] = participants2.loc[:, 'Full_name'].apply(cap_word)
participants2

first      last  Age    profession      Full_name      Index_profi  \
a  Миша    Нечаев   30          Chef    Миша Нечаев          16 Chef   
b  Саша  Васильев   46        Driver  Саша Васильев        32 Driver   
c  Эдик   Романов   32   ElEctRiCiAn   Эдик Романов   18 Electrician   
d  Ваня  Николаев   54  ProgrammerML       AhmedovF  40 ProgrammerML   
e  Петя   Смирнов   31   Hairdresser   Петя Смирнов   17 Hairdresser   
f  Коля  Труфанов   62     Architect  Коля Труфанов     48 Architect   

              Eng  
a   Misha Nechaev  
b  Sasha Vasil'ev  
c    Edik Romanov  
d        AhmedovF  
e   Petya Smirnov  
f  Kolya Trufanov

In [ ]:
participants2['Length'] = participants2.loc[:, 'Full_name'].apply(len)
participants2

first      last  Age    profession      Full_name      Index_profi  \
a  Миша    Нечаев   30          Chef    Миша Нечаев          16 Chef   
b  Саша  Васильев   46        Driver  Саша Васильев        32 Driver   
c  Эдик   Романов   32   ElEctRiCiAn   Эдик Романов   18 Electrician   
d  Ваня  Николаев   54  ProgrammerML       AhmedovF  40 ProgrammerML   
e  Петя   Смирнов   31   Hairdresser   Петя Смирнов   17 Hairdresser   
f  Коля  Труфанов   62     Architect  Коля Труфанов     48 Architect   

              Eng  Length  
a   Misha Nechaev      11  
b  Sasha Vasil'ev      13  
c    Edik Romanov      12  
d        AhmedovF       8  
e   Petya Smirnov      12  
f  Kolya Trufanov      13

In [ ]:
participants2['LowerCase'] = participants2.loc[:, 'Full_name'].apply(lambda x: x.lower())
participants2

first      last  Age    profession      Full_name      Index_profi  \
a  Миша    Нечаев   30          Chef    Миша Нечаев          16 Chef   
b  Саша  Васильев   46        Driver  Саша Васильев        32 Driver   
c  Эдик   Романов   32   ElEctRiCiAn   Эдик Романов   18 Electrician   
d  Ваня  Николаев   54  ProgrammerML       AhmedovF  40 ProgrammerML   
e  Петя   Смирнов   31   Hairdresser   Петя Смирнов   17 Hairdresser   
f  Коля  Труфанов   62     Architect  Коля Труфанов     48 Architect   

              Eng  Length      LowerCase  
a   Misha Nechaev      11    миша нечаев  
b  Sasha Vasil'ev      13  саша васильев  
c    Edik Romanov      12   эдик романов  
d        AhmedovF       8       ahmedovf  
e   Petya Smirnov      12   петя смирнов  
f  Kolya Trufanov      13  коля труфанов

In [ ]:
def add_exclamation(last):
  return last + ' !!!'

participants2['last_exclaimed'] = participants2['last'].apply(add_exclamation)
participants2

first      last  Age    profession      Full_name      Index_profi  \
a  Миша    Нечаев   30          Chef    Миша Нечаев          16 Chef   
b  Саша  Васильев   46        Driver  Саша Васильев        32 Driver   
c  Эдик   Романов   32   ElEctRiCiAn   Эдик Романов   18 Electrician   
d  Ваня  Николаев   54  ProgrammerML       AhmedovF  40 ProgrammerML   
e  Петя   Смирнов   31   Hairdresser   Петя Смирнов   17 Hairdresser   
f  Коля  Труфанов   62     Architect  Коля Труфанов     48 Architect   

              Eng  Length      LowerCase last_exclaimed  
a   Misha Nechaev      11    миша нечаев     Нечаев !!!  
b  Sasha Vasil'ev      13  саша васильев   Васильев !!!  
c    Edik Romanov      12   эдик романов    Романов !!!  
d        AhmedovF       8       ahmedovf   Николаев !!!  
e   Petya Smirnov      12   петя смирнов    Смирнов !!!  
f  Kolya Trufanov      13  коля труфанов   Труфанов !!!

In [ ]:
import pandas as pd

data = {'text': ['Hello', 'World', 'Pandas']}
df = pd.DataFrame(data)

df['text_length'] = df['text'].apply(len)
print(df)


     text  text_length
0   Hello            5
1   World            5
2  Pandas            6


In [ ]:
df['text_lower'] = df['text'].apply(lambda x: x.lower())
print(df)


     text  text_length text_lower
0   Hello            5      hello
1   World            5      world
2  Pandas            6     pandas


In [ ]:
# The end