In [6]:
import numpy as np

In [8]:
array4 = np.empty(3)
print(array4)

[1. 1. 1.]


In [9]:
array5 = np.arange(5)
print(array5)

[0 1 2 3 4]


In [7]:
# مصفوفة من نطاق الأعداد
array5 = np.arange(3)
print(array5)
# الناتج: array([0, 1, 2])


[0 1 2]


In [13]:
# مصفوفة من الأصفار بعدد 3
array_zeros = np.zeros((3, 3))  # مصفوفة 3x3 من الأصفار
print(array_zeros)

# مصفوفة من الواحدات بعدد 3
array_ones = np.ones((2, 2))  # مصفوفة 2x2 من الواحدات
print("\n", array_ones)

# مصفوفة غير مهيأة
array_empty = np.empty((4, 4))  # مصفوفة 4x4 غير مهيأة
print("\n", array_empty)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 [[1. 1.]
 [1. 1.]]

 [[2.95592934e-316 0.00000000e+000 2.41907520e-312 2.37663529e-312]
 [2.22809558e-312 2.46151512e-312 6.79038654e-313 2.35541533e-312]
 [2.46151512e-312 6.79038654e-313 2.35541533e-312 6.79038654e-313]
 [2.14321575e-312 2.22809558e-312 2.14321575e-312 0.00000000e+000]]
