In [6]:
import numpy as np

In [8]:
array4 = np.empty(3)
print(array4)

[1. 1. 1.]


In [9]:
array5 = np.arange(5)
print(array5)

[0 1 2 3 4]


In [7]:
# مصفوفة من نطاق الأعداد
array5 = np.arange(3)
print(array5)
# الناتج: array([0, 1, 2])


[0 1 2]


In [13]:
# مصفوفة من الأصفار بعدد 3
array_zeros = np.zeros((3, 3))  # مصفوفة 3x3 من الأصفار
print(array_zeros)

# مصفوفة من الواحدات بعدد 3
array_ones = np.ones((2, 2))  # مصفوفة 2x2 من الواحدات
print("\n", array_ones)

# مصفوفة غير مهيأة
array_empty = np.empty((4, 4))  # مصفوفة 4x4 غير مهيأة
print("\n", array_empty)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 [[1. 1.]
 [1. 1.]]

 [[2.95592934e-316 0.00000000e+000 2.41907520e-312 2.37663529e-312]
 [2.22809558e-312 2.46151512e-312 6.79038654e-313 2.35541533e-312]
 [2.46151512e-312 6.79038654e-313 2.35541533e-312 6.79038654e-313]
 [2.14321575e-312 2.22809558e-312 2.14321575e-312 0.00000000e+000]]


In [14]:
# إنشاء مصفوفة حجمها 1000x1000
large_array_empty = np.empty((1000, 1000))  # مصفوفة كبيرة غير مهيأة
large_array_empty

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [15]:
import numpy as np

oned = np.arange(21)

print("نوع البيانات:", oned.dtype)  # نوع البيانات
print("عدد العناصر:", oned.size)    # عدد العناصر
print("حجم الذاكرة:", oned.nbytes)   # حجم الذاكرة (بالبايت) المستخدم من قبل عناصر المصفوفة
print("شكل المصفوفة:", oned.shape)   # عدد العناصر في كل بُعد
print("عدد الأبعاد:", oned.ndim)      # عدد الأبعاد

نوع البيانات: int64
عدد العناصر: 21
حجم الذاكرة: 168
شكل المصفوفة: (21,)
عدد الأبعاد: 1


In [19]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

print(matrix, "\n")
print("شكل:", matrix.shape)        # الشكل: (4, 4)
print("عدد الأبعاد:", matrix.ndim)  # عدد الأبعاد: 2


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

شكل: (4, 4)
عدد الأبعاد: 2


In [22]:
# إعادة تشكيل المصفوفة إلى مصفوفة أحادية البعد
reshaped_1d = matrix.reshape(16)
print(reshaped_1d, "\n")

# إعادة تشكيل المصفوفة إلى مصفوفة ثنائية الأبعاد (2 × 8)
reshaped_2d = matrix.reshape(2, 8)
print(reshaped_2d, "\n")

# إعادة تشكيل المصفوفة إلى مصفوفة بأبعاد متعددة (2 × 2 × 2 × 2)
new_array = matrix.reshape(2, 2, 2, 2)
print(new_array, "\n")
print("شكل:", new_array.shape, "\n")      # الشكل: (2, 2, 2, 2)
print("عدد الأبعاد:", new_array.ndim, "\n")  # عدد الأبعاد: 4


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16] 

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]] 

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]] 

شكل: (2, 2, 2, 2) 

عدد الأبعاد: 4 



In [23]:
import numpy as np

one = np.arange(10)
print("عنصر المصفوفة 1D بالفهرس 3 (بدءًا من 0):", one[3])
print("آخر عنصر في المصفوفة 1D (أو الأول من النهاية):", one[-1])
print("تقطيع عناصر المصفوفة 1D (من 3 إلى 8 غير شامل):", one[3:8])


عنصر المصفوفة 1D بالفهرس 3 (بدءًا من 0): 3
آخر عنصر في المصفوفة 1D (أو الأول من النهاية): 9
تقطيع عناصر المصفوفة 1D (من 3 إلى 8 غير شامل): [3 4 5 6 7]


In [24]:
two = np.arange(21).reshape(3, 7)  # إنشاء مصفوفة 3 × 7
print("الحصول على الصف الثاني:", two[2])  # العد يبدأ من الصفر
print("الحصول على العنصر في الصف 2 والعمود 4:", two[2, 4])  # العد يبدأ من الصفر
print("الحصول على الصفين 0 و 1:", two[0:2])  # نطاقات في بايثون تشمل القيمة الابتدائية ولا تشمل النهاية
print("الحصول على العمود 5 من جميع الصفوف:", two[:, 5])
print("الحصول على آخر ثلاثة أعمدة من الصفين 1 و 2:", two[1:3, -3:])

الحصول على الصف الثاني: [14 15 16 17 18 19 20]
الحصول على العنصر في الصف 2 والعمود 4: 18
الحصول على الصفين 0 و 1: [[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]]
الحصول على العمود 5 من جميع الصفوف: [ 5 12 19]
الحصول على آخر ثلاثة أعمدة من الصفين 1 و 2: [[11 12 13]
 [18 19 20]]


In [25]:
# تحديث قيمة المصفوفة في الصف 0 والعمود 0
two[0, 0] = 33
print(two)

# ملء الأعمدة الثلاثة الأولى بالأصفار، بدءًا من الصف 1
two[1:, :3] = 0
print(two)

[[33  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]
[[33  1  2  3  4  5  6]
 [ 0  0  0 10 11 12 13]
 [ 0  0  0 17 18 19 20]]
