Tasks

In [ ]:
import numpy as np

# Create an array with shape (3, 4)
data = np.arange(12).reshape(3, 4)
print("data:\n", data)
print("Minimum value:", data.min())       # Minimum value
print("Sum of all values:", data.sum())   # Sum of all values
print("Mean value:", data.mean())         # Mean value
print("Standard deviation:", data.std())   # Standard deviation
print("Maximum value:", data.max())       # Maximum value

print("Sum of each row:", data.sum(axis=1))   # Sum along axis 1 - result for each row
print("Sum of each column:", data.sum(axis=0)) # Sum along axis 0 - result for each column

print("Standard deviation of each row:", data.std(axis=1))   # Standard deviation of each row
print("Standard deviation of each column:", data.std(axis=0)) # Standard deviation of each column

print("Index of the maximum element of each row:", data.argmax(axis=1))   # Index of the maximum element in each row
print("Index of the maximum element of each column:", data.argmax(axis=0)) # Index of the maximum element in each column

print("Maximum element of each row:", data.max(axis=1))   # Maximum element in each row
print("Maximum element of each column:", data.max(axis=0)) # Maximum element in each column


data:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Minimum value: 0
Sum of all values: 66
Mean value: 5.5
Standard deviation: 3.452052529534663
Maximum value: 11
Sum of each row: [ 6 22 38]
Sum of each column: [12 15 18 21]
Standard deviation of each row: [1.11803399 1.11803399 1.11803399]
Standard deviation of each column: [3.26598632 3.26598632 3.26598632 3.26598632]
Index of the maximum element of each row: [3 3 3]
Index of the maximum element of each column: [2 2 2 2]
Maximum element of each row: [ 3  7 11]
Maximum element of each column: [ 8  9 10 11]


In [4]:
# Матричные операции

# Create another array A1
A1 = np.arange(9).reshape(3, 3)
print("A1:\n", A1)
print("Transposed A:\n", A1.T)  # Transpose

# Create an array A2
A2 = np.ones(9).reshape(3, 3)
print("A1 @ A2:\n", A1 @ A2)  # Matrix multiplication

print("Dot product:\n", A1.dot(A2))  # Dot product
print("Diagonal of the matrix:\n", A1.diagonal())  # Diagonal of the matrix

A1:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Transposed A:
 [[0 3 6]
 [1 4 7]
 [2 5 8]]
A1 @ A2:
 [[ 3.  3.  3.]
 [12. 12. 12.]
 [21. 21. 21.]]
Dot product:
 [[ 3.  3.  3.]
 [12. 12. 12.]
 [21. 21. 21.]]
Diagonal of the matrix:
 [0 4 8]


In [5]:
print("Data type:", A1.dtype)
print("Number of elements:", A1.size)
print("Memory occupied:", A1.nbytes)

# Create an array with int8 type
C = np.arange(9, dtype=np.int8).reshape(3, 3)
print("Data type:", C.dtype)
print("Number of elements:", C.size)
print("Memory occupied:", C.nbytes)

Data type: int64
Number of elements: 9
Memory occupied: 72
Data type: int8
Number of elements: 9
Memory occupied: 9


In [7]:
import numpy as np

# إنشاء مصفوفة A1
A1 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# إنشاء مصفوفة A2
A2 = np.array([[1, 1, 1],
                [1, 1, 1],
                [1, 1, 1]])

print("A1:\n", A1)
print("A2:\n", A2)
print(f"A1 {A1.shape} + A2 {A2.shape} = A3 {(A1 + A2).shape}:\n", A1 + A2)

A1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
A2:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
A1 (3, 3) + A2 (3, 3) = A3 (3, 3):
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [8]:
A2 = np.array([1, 1, 1])
print("A1:\n", A1)
print("A2:\n", A2)
print(f"A1 {A1.shape} + A2 {A2.shape} = A3 {(A1 + A2).shape}:\n", A1 + A2)

A1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
A2:
 [1 1 1]
A1 (3, 3) + A2 (3,) = A3 (3, 3):
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [9]:
A2 = 1
print("A1:\n", A1)
print("A2:\n", A2)
print(f"A1 {A1.shape} + A2 (int) = A3 {(A1 + A2).shape}:\n", A1 + A2)

A1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
A2:
 1
A1 (3, 3) + A2 (int) = A3 (3, 3):
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [10]:
A1 = np.arange(10).reshape(2, 1, 5)
A2 = np.arange(14).reshape(2, 7, 1)
print("A1:\n", A1)
print("A2:\n", A2)
print(f"A1 {A1.shape} + A2 {A2.shape} = A3 {(A1 + A2).shape}:\n", A1 + A2)

# Result
# A1:
#  [[[0 1 2 3 4]]
#
#  [[5 6 7 8 9]]]
# A2:
#  [[[ 0]
#   [ 1]
#   [ 2]
#   [ 3]
#   [ 4]
#   [ 5]
#   [ 6]]
#
#  [[ 7]
#   [ 8]
#   [ 9]
#   [10]
#   [11]
#   [12]
#   [13]]]
# A1 (2, 1, 5) + A2 (2, 7, 1) = A3 (2, 7, 5):
#  [[[ 0  1  2  3  4]
#   [ 1  2  3  4  5]
#   [ 2  3  4  5  6]
#   [ 3  4  5  6  7]
#   [ 4  5  6  7  8]
#   [ 5  6  7  8  9]
#   [ 6  7  8  9 10]]
#
#  [[12 13 14 15 16]
#   [13 14 15 16 17]
#   [14 15 16 17 18]
#   [15 16 17 18 19]
#   [16 17 18 19 20]
#   [17 18 19 20 21]
#   [18 19 20 21 22]]]


A1:
 [[[0 1 2 3 4]]

 [[5 6 7 8 9]]]
A2:
 [[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]
  [10]
  [11]
  [12]
  [13]]]
A1 (2, 1, 5) + A2 (2, 7, 1) = A3 (2, 7, 5):
 [[[ 0  1  2  3  4]
  [ 1  2  3  4  5]
  [ 2  3  4  5  6]
  [ 3  4  5  6  7]
  [ 4  5  6  7  8]
  [ 5  6  7  8  9]
  [ 6  7  8  9 10]]

 [[12 13 14 15 16]
  [13 14 15 16 17]
  [14 15 16 17 18]
  [15 16 17 18 19]
  [16 17 18 19 20]
  [17 18 19 20 21]
  [18 19 20 21 22]]]


In [ ]:
import numpy as np

array1 = np.array([4, 8, 9])
array2 = np.array([1, 2, 3])

print("Element-wise multiplication:", array1 * array2)
print("Element-wise addition:", array1 + array2)
print("Element-wise subtraction:", array1 - array2)

Element-wise multiplication: [ 4 16 27]
Element-wise addition: [ 5 10 12]
Element-wise subtraction: [3 6 6]
Element-wise division: [4. 4. 3.]


In [ ]:
import numpy as np

In [ ]:
array4 = np.empty(3)
print(array4)

[1. 1. 1.]


In [ ]:
array5 = np.arange(5)
print(array5)

[0 1 2 3 4]


In [3]:
array5 = np.arange(3)
print(array5)

[0 1 2]


In [ ]:
array_zeros = np.zeros((3, 3))
print(array_zeros)

array_ones = np.ones((2, 2))
print("\n", array_ones)

array_empty = np.empty((4, 4))
print("\n", array_empty)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 [[1. 1.]
 [1. 1.]]

 [[2.95592934e-316 0.00000000e+000 2.41907520e-312 2.37663529e-312]
 [2.22809558e-312 2.46151512e-312 6.79038654e-313 2.35541533e-312]
 [2.46151512e-312 6.79038654e-313 2.35541533e-312 6.79038654e-313]
 [2.14321575e-312 2.22809558e-312 2.14321575e-312 0.00000000e+000]]


In [ ]:
large_array_empty = np.empty((1000, 1000))
large_array_empty

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
import numpy as np

oned = np.arange(21)

print("نوع البيانات:", oned.dtype)
print("عدد العناصر:", oned.size)
print("حجم الذاكرة:", oned.nbytes)
print("شكل المصفوفة:", oned.shape)
print("عدد الأبعاد:", oned.ndim)

نوع البيانات: int64
عدد العناصر: 21
حجم الذاكرة: 168
شكل المصفوفة: (21,)
عدد الأبعاد: 1


In [ ]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

print(matrix, "\n")
print("شكل:", matrix.shape)
print("عدد الأبعاد:", matrix.ndim)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

شكل: (4, 4)
عدد الأبعاد: 2


In [ ]:
reshaped_1d = matrix.reshape(16)
print(reshaped_1d, "\n")

reshaped_2d = matrix.reshape(2, 8)
print(reshaped_2d, "\n")

new_array = matrix.reshape(2, 2, 2, 2)
print(new_array, "\n")
print("شكل:", new_array.shape, "\n")
print("عدد الأبعاد:", new_array.ndim, "\n")


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16] 

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]] 

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]] 

شكل: (2, 2, 2, 2) 

عدد الأبعاد: 4 



In [ ]:
import numpy as np

one = np.arange(10)
print("عنصر المصفوفة 1D بالفهرس 3 (بدءًا من 0):", one[3])
print("آخر عنصر في المصفوفة 1D (أو الأول من النهاية):", one[-1])
print("تقطيع عناصر المصفوفة 1D (من 3 إلى 8 غير شامل):", one[3:8])


عنصر المصفوفة 1D بالفهرس 3 (بدءًا من 0): 3
آخر عنصر في المصفوفة 1D (أو الأول من النهاية): 9
تقطيع عناصر المصفوفة 1D (من 3 إلى 8 غير شامل): [3 4 5 6 7]


In [ ]:
two = np.arange(21).reshape(3, 7)  # إنشاء مصفوفة 3 × 7
print("الحصول على الصف الثاني:", two[2])  # العد يبدأ من الصفر
print("الحصول على العنصر في الصف 2 والعمود 4:", two[2, 4])  # العد يبدأ من الصفر
print("الحصول على الصفين 0 و 1:", two[0:2])  # نطاقات في بايثون تشمل القيمة الابتدائية ولا تشمل النهاية
print("الحصول على العمود 5 من جميع الصفوف:", two[:, 5])
print("الحصول على آخر ثلاثة أعمدة من الصفين 1 و 2:", two[1:3, -3:])

الحصول على الصف الثاني: [14 15 16 17 18 19 20]
الحصول على العنصر في الصف 2 والعمود 4: 18
الحصول على الصفين 0 و 1: [[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]]
الحصول على العمود 5 من جميع الصفوف: [ 5 12 19]
الحصول على آخر ثلاثة أعمدة من الصفين 1 و 2: [[11 12 13]
 [18 19 20]]


In [ ]:
two[0, 0] = 33
print(two)

two[1:, :3] = 0
print(two)

[[33  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]
[[33  1  2  3  4  5  6]
 [ 0  0  0 10 11 12 13]
 [ 0  0  0 17 18 19 20]]


In [1]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]
result = [a + b for a, b in zip(list1, list2)]
print(result)  # [5, 7, 9]

[5, 7, 9]


In [2]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
result = array1 + array2
print(result)  # [5 7 9]

[5 7 9]


In [8]:
# الطرح
result_sub = array1 - array2  # [-3 -3 -3]
print(result_sub)

# الضرب
result_mul = array1 * array2  # [ 4 10 18]
print(result_mul
      )
# القسمة
result_div = array1 / array2  # [0.25 0.4 0.5]
print(result_div)

[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [10]:
bool_array1 = np.array([True, False, True])
bool_array2 = np.array([False, False, True])
result_logical = bool_array1 & bool_array2  # [False False  True]
result_logical

array([False, False,  True])

In [1]:
import numpy as np

# Create an array A with shape (4, 6)
a = np.arange(24).reshape(4, 6)
print("Array A:\n", a)

# Create a view B from A
b = a[:2, 3:]
print("Array B:\n", b)

# Modify an element in B
b[1, 2] = -1
print("Array B after modification:\n", b)
print("Array A after modification:\n", a)

Array A:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Array B:
 [[ 3  4  5]
 [ 9 10 11]]
Array B after modification:
 [[ 3  4  5]
 [ 9 10 -1]]
Array A after modification:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 -1]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [2]:
# Create a copy of B
b = a[:2, 3:].copy()  # Make a copy
print("Array B (copy):\n", b)

# Modify an element in the copy
b[1, 2] = -1
print("Array B after modification (copy):\n", b)
print("Array A after modification (copy):\n", a)

Array B (copy):
 [[ 3  4  5]
 [ 9 10 -1]]
Array B after modification (copy):
 [[ 3  4  5]
 [ 9 10 -1]]
Array A after modification (copy):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 -1]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
